version: '3'

services:

  sql_influx:
    container_name: sql_influx
    build: ./sql_influx
    command: python main.py
    hostname: ${hostname}
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /etc/pihole/:/etc/pihole
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    hostname: ${hostname}
    environment:
      - HOST_MOUNT_PREFIX=/hostfs
      - HOST_PROC=/hostfs/proc
    devices:
      - /dev/vchiq
      - /dev/vcsm
    volumes:
      - ./telegraf:/etc/telegraf
      - /opt/vc:/opt/vc
      - /:/hostfs:ro
      - /run/udev:/run/udev:ro
    restart: unless-stopped